version: 0.1
phases:
  install:
    commands:
      - echo installing nothing...
  pre_build:
    commands:
      - echo installing dependencies...
      - pwd
  build:
    commands:
      # - echo testing...
      # - echo building...
      - ls -l
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: bin/
